[package]
authors = ["Me <Me>"]
edition = "2018"
name = "slurm-harray"
version = "0.1.0"

[dependencies]
anyhow = "^1.0"
base-62 = "^0.1"
serde = { version="^1.0", features = ["derive"] }
serde_json = { version = "^1.0", features = ["preserve_order"] }
sha2 = "^0.9"
structopt = "^0.3"